### ISSUE TITLE
no ../outputs/filtered_subjects_df.csv file present

### ISSUE THREAD

**Issue by gabywh** [AmirDavoodi/ASD-GraphNet#1]
Hi,

Loved the write-up, the git repo and the instructions for obtaining datasets.

I got all the python virtual env set up etc
Trying to run for first time e.g. 
`python3 experiments/run_shap_analysis.py`

and I get

```
  File "[...]ASD-GraphNet/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../outputs/filtered_subjects_df.csv'
```

I also tried e.g. 
`python3 experiments/test_data_loading.py`
and I get - unsurprisingly - the same error message about the same file missing.

```
$ ls outputs/
50617_aal_adjacency_matrix.png		     outpipeline_results_df.csv
50617_cc200_adjacency_matrix.png	     shap_analysis
50617_dos160_adjacency_matrix.png	     shap_beeswarm_plot.png
51154_aal_adjacency_matrix.png		     shap_dependence_plots.png
51154_cc200_adjacency_matrix.png	     shap_feature_importance_bar.png
51154_dos160_adjacency_matrix.png	     shap_feature_importance.png
comprehensive_feature_importance.csv	     shap_force_asd_case.png
connectome_patient_50617_nx_graph_aal.png    shap_force_tdc_case.png
connectome_patient_50617_nx_graph_cc200.png  shap_stacked_force_plot.html
edge_based_features.csv			     shap_summary_plot.png
filtered_subjects_df.csv		     shap_summary.png
graph_level_features.csv		     shap_waterfall_asd_case.png
importance_vs_difference.png		     shap_waterfall_tdc_case.png
node_based_features.csv			     site_id_distribution.png
outpipeline_full_training_results_df.csv     site_stratification_analysis.csv

```
- no filtered_subjects_df.csv is present, maybe just missing from the git repo?

**Comment by AmirDavoodi** [comment]
Sorry for the very very late reply.

I was having kidney surgery and two month off.

I hope you have fixed the problems by yourself.

Thanks for the PRs. I merged them thanks to your help.

I hope your research and possible published paper includes our paper as the reference.

**Comment by gabywh** [comment]
No, not fixed... I did something of a hack job to generate what I thought should probably the contents of the `outputs/filtered_subjects_df.csv` file, but was just a best-guess from me.. if you have a sample `filtered_subjects_df.csv` file you could somehow supply that would help me enormously - happy to fix up the code and submit a PR for you

Should I get to publish, for sure will mention this paper.

What interests me here is the _relatively_ low classification rate of ca 70%, I'm pretty sure it can be better, so at the moment I'm just playing around with ideas, modding (sometimes quite heavily) the source code here, etc.
